---
pips_utils::environment_whitelist:
- ro1-cust-alpha-d1
- ro1-mnm-b2b-d1
- ro1-mnm-b2b-s1
- sy2-cust-alpha-d2
- sy2-cust-alpha-d3
- sy2-cust-alpha-s1
- sy2-e2e-b2b-d1
- sy2-e2e-b2b-s1
- sy2-e2e-b2b-p1
- sy2-e2e2-b2c-d1
- sy2-e2e2-b2c-s1
- sy2-e2e2-b2c-p1
- inv-d
